### ISSUE TITLE
"Node requires node_modules and npm" is not true and correct

### ISSUE THREAD

**Issue by guest271314** [j50n/deno-proc#29]
I fetch the Node.js nightly binary release, extract `node` executable and run that extracted `node` executable without using `npm` or `node_modules` whatsoever https://github.com/guest271314/download-node-nightly-executable.

**Comment by j50n** [comment]
I am changing the wording a bit from "requires" to "typically uses." I am not quite sure what the original bug report was getting at, since it was a complaint about the wording without a suggestion to fix. Also not sure why the original bug report ended up on the denoland repo.

**Comment by guest271314** [comment]
> I am changing the wording a bit from "requires" to "typically uses." I am not quite sure what the original bug report was getting at, since it was a complaint about the wording without a suggestion to fix. 

`node` does not require `node_modules` or `npm` to run at all. 

"typically" is not true and correct either. I run the `node` executable here https://github.com/guest271314/native-messaging-nodejs using `.mjs` extension without `node_modules`, `npm`, or `package.json`.

> Also not sure why the original bug report ended up on the denoland repo.

Because when I originally read the description of your module on the deno.land Web site it was not clear that deno.land hosted third-party modules, thus I thought this was a module published by Deno itself and filed an issue there re documentation.

The phrase can be completely removed for accuracy.

**Comment by guest271314** [comment]
This is what I originally observed on deno.land: 
![210295062-dc241e0e-d2ea-4dce-8ca6-283a99dfa464](https://user-images.githubusercontent.com/4174848/218325973-cbd0a252-3308-4d5b-8346-27b2699b6b6d.png)



Note the absense of the "x" in the URL in the address bar. At that time I didn't even know deno.land hosted third-party modules on the "x" path on their Web site. 

It doesn't really matter though. The claim is simply not true, whether Deno or anybody else authored the claim.

**Comment by j50n** [comment]
Is there any chance you can point me to an example where there are external dependencies? The one you pointed me to only uses a node-native import. I am genuinely curious now how you would manage versioned imports using node without a package file. I use node myself, so this is an intriguing thought.

**Comment by guest271314** [comment]
> Is there any chance you can point me to an example where there are external dependencies?

The idea for me is to run and test JavaScript engines (Node.js, Deno, QuickJS, txiki.js, Bun) standalone _without_ any external dependencies.

If I really need to import code I just use `import`. I have no use for `npm` or `node_modules` or `package.json` and neither are actually necessary to run the `node` executable.

>  I am genuinely curious now how you would manage versioned imports using node without a package file.

Just use Ecmascript/WHATWG HTML `import`.

**Comment by guest271314** [comment]
The one caveat and Node.js specific artifact of CommonJS is the file needs to have an `.mjs` extension  for `import` to work and not make Node.js loader throw. So we would either need to import from jsdelivr, unpkg, etc. files with a `.mjs` extension, or fetch the `.js` file then create the file locally with `.mjs` extension or use other means to deal with Node.js specific behaviour re their loader.

That is a Node.js legacy limitation. Nonetheless possible to work around without using `node_modules`, `npm`, or `package.json`.

My interest in this matter is the claim that `node_modules` and `npm` are _required_, to run `node`, which is not technically true and correct.

Correct documentation is important to me. I vet any and all claims that are not true and correct, no matter who makes them.

How to deal with Node.js specific artifacts is a separate matter. There are workarounds. It took me a while to figure out we didn't even need `{type:"module", "main":"nm_nodes.js"}` in `package.json` or `package.json` at all when `.mjs` extension was used. 

Now that _is_ a true and correct description that Node.js requires `.mjs` extension to `import` _without_ a `package.json` file, at least the last time I checked using Node.js nightly download. `node_modules` and `npm` are not required at all to run the `node` executable.

**Comment by j50n** [comment]
You are correct that the word "require" was incorrect. This has been changed.

**Comment by guest271314** [comment]
"typical" is not correct either. You can download the Node.js nightly `node` executable here https://github.com/guest271314/download-node-nightly-executable and run `node` without `node_modules` or `npm`.

What is the purpose of making that claim? It is not necessary to claim that Node.js "typically" uses this or that to compare to Deno.

**Comment by guest271314** [comment]
With Node.js you can "just run the script", too - as long as the script has an `.mjs` extension. I would point out that current reality instead of trying to claim that Node.js "typically uses" `node_modules` and `npm`. Those are _choices_, not mandatory.
